### ISSUE TITLE
`x new vue-nuxt ProjectName` should create a folder and nest the new project in it.

### ISSUE THREAD

**Issue by VictorioBerra** [NetCoreTemplates/vue-nuxt#24]
Exactly like `dotnet new mvc --name ProjectName` works. It creates a folder called /ProjectName and all files are created in that path.

I did not expect it to dump out all the files right in my working directory.

**Comment by mythz** [comment]
This was previously the behavior but was changed because it would create an unwanted directory when creating a project into a new Git Repo but I've just changed it back so that specifying a ProjectName now creates a new top-level folder (not specifying a project name doesn't), so these are now equivalent:

    $ x new vue-nuxt ProjectName

and 

    $ mkdir ProjectName && cd ProjectName
    $ x new vue-nuxt

This change is available from v5.1.19+ of `x` and `app` tools, update to latest version with:

    $ dotnet tool update -g x
