### ISSUE TITLE
does it work as Azure web app

### ISSUE THREAD

**Issue by DealerCorp** [NetCoreTemplates/vue-nuxt#3]

**Comment by mythz** [comment]
I have no idea what this is supposed to mean? it's a valid .NET Core App that you can run and publish like any other .NET Core App, any issues you're having is likely with how it's being deployed or configured. 

In the end .NET Core Apps are just Console Apps. If you can run the published outputs with:

     $ npm run publish
     $ cd bin/Release/netcoreapp2.1/publish
     $ dotnet MyApp.dll

Then the .NET Core App works as it's supposed to and the issue is somewhere else.

FYI https://techstacks.io was developed using this template.

**Comment by DealerCorp** [comment]
Thanks, it works after deployed to Azure as a web app

**Comment by mythz** [comment]
Oh this was a question? this looked like it was trying to report a vague issue.

Yes it works and can be deployed like any other .NET Core Web App (since that's all it is).

In future please use the [Customer Forums](https://forums.servicestack.net/) or ask a question on StackOverflow with the `#servicestack` hash tag if you have any questions.

**Comment by DealerCorp** [comment]
is the source code in your template free to use or any limit?

**Comment by DealerCorp** [comment]
what is 10 Operations in ServiceStack?
could you give out more explanation?

**Comment by mythz** [comment]
10x Request DTOs, aka ServiceStack Services.

E.g. http://templates.servicestack.net and  https://gistlyn.com only use 10 Custom (i.e. non built-in ServiceStack) Services so they can be used without registering a license key.  You can view each of their Services on their metadata pages:

 - http://templates.servicestack.net/metadata
 - https://gistlyn.com/metadata

If they had more than 10 Services they would need a commercial license to be able to run them.
